import turtle
i=0
turtle.speed(7)
turtle.color("green")
turtle.pensize(2500)
turtle.forward(1)
turtle.color("yellow")
turtle.forward(1)
turtle.color("blue")
turtle.forward(1)
turtle.color("black")
turtle.forward(1)
turtle.right(180)
turtle.forward(0)
turtle.pensize(25)
turtle.goto(330,80)